# permissions for end users to edit sparkhistoryservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-edit: "true"
  name: sparkhistoryserver-editor-role
rules:
- apiGroups:
  - kubricks.kubricks.io
  resources:
  - sparkhistoryservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubricks.kubricks.io
  resources:
  - sparkhistoryservers/status
  verbs:
  - get
