# permissions for end users to view sparkhistoryservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sparkhistoryserver-viewer-role
rules:
- apiGroups:
  - kubricks.kubricks.io
  resources:
  - sparkhistoryservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubricks.kubricks.io
  resources:
  - sparkhistoryservers/status
  verbs:
  - get
